services:
  backend:
    build:
      context: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MOCK_MODE: "true"  #Switch between mock data and AWS data 
    restart: unless-stopped

  frontend:
    build:
      context: ./infrastructure-dashboard-ui
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:5000/api/metrics"
    depends_on:
      - backend
    restart: unless-stopped
