#Prototype Compose file, to be modified once AWS is applied 

# version: "3.9"

# services:
#   backend:
#     build:
#       context: ./backend
#     container_name: flask_backend
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=production
#     restart: unless-stopped

#   frontend:
#     build:
#       context: ./infrastructure-dashboard-ui
#     container_name: nextjs_frontend
#     ports:
#       - "3000:3000"
#     environment:
#       NEXT_PUBLIC_API_URL: "http://backend:5000"
#     depends_on:
#       - backend
#     restart: unless-stopped
