services:
  backend:
    build:
      context: ./backend
    container_name: flask_backend_dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
    command: ["python", "app.py"]

  frontend:
    build:
      context: ./infrastructure-dashboard-ui
    container_name: nextjs_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure-dashboard-ui:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5000/api/metrics"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
